- name: Install Steam
  become: yes
  apt:
    deb: https://repo.steampowered.com/steam/archive/precise/steam_latest.deb

- name: Install steam dependencies
  become: yes
  apt:
    name: '{{ item }}'
  loop:
    - libc6:amd64
    - libc6:i386
    - libegl1:amd64
    - libegl1:i386
    - libgbm1:amd64
    - libgbm1:i386
    - libgl1-mesa-dri:amd64
    - libgl1-mesa-dri:i386
    - libgl1:amd64
    - libgl1:i386
    - steam-libs-amd64:amd64
    - steam-libs-i386:i386