- name: Install calibre
  become: yes
  block:
    - name: Get Calibre installer
      get_url:
        url: https://download.calibre-ebook.com/linux-installer.sh
        dest: /tmp/calibre-installer.sh
        mode: 700

    - name: Run calibre installer
      script: /tmp/calibre-installer.sh

    - name: Remove calibre installer
      file:
        path: /tmp/calibre-installer.sh
        state: absent


