- name: Copy user-dirs.dirs
  copy:
    src: roles/gnome/files/user-dirs.dirs
    dest: "/home/{{ user }}/.config/user-dirs.dirs"
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: 0600

- name: GNOME Settings
  dconf:
    key: "{{ setting.key }}"
    value: "{{ setting.value }}"
  loop: '{{ settings | dict2items }}'
  loop_control:
    loop_var: setting